spring:
  datasource:
         url: jdbc:mysql://10.0.21.108:3306/yl_cxk
         userName: root
         password: root
  thymeleaf:
         cache: true
         check-template-location: true
         enabled: true
         encoding: utf-8
         mode: HTML5
         prefix: classpath:/templates/
         suffix: .html
         servlet:
           content-type: text/html
  cache:
        ehcache:
          config:  classpath:/ehcache.xml
debug:
   true
mybatis:
  mapper-locations:  classpath:/mapping/*Mapper.xml
logging:
# 打印sql
  level:
     com.example.demo.dao : debug
#     com.example.demo.controller: debug       
